### ISSUE TITLE
Traffic Out showing 493MB but the actual value is 493KB

### ISSUE THREAD

**Issue by itzgeekweb** [alexandermarston/vnstat-dashboard#1]
Hello Alex,

Please find attached screen shot. Traffic out is only 493KB but in the graph it is showing as 493MB. Text value is proper below the graph.
![vnstat dashboard](https://cloud.githubusercontent.com/assets/20610625/20380729/dbdcd310-acc9-11e6-915c-000c2adcb85c.JPG)

**Comment by alexandermarston** [comment]
This should now have been fixed as in b3237d2.
