### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by alexandermarston** [alexandermarston/vnstat-dashboard#14]
The PHP code behind this project could use with some refactoring.

This issue is open for any PRs to improve code quality.

**Comment by mkingbe** [comment]
WIP

**Comment by bashilbers** [comment]
Why don't you separate the business logic and the view? I can help you setup a nice Vue application if you want

**Comment by alexandermarston** [comment]
The codebase has been refactored under commit 5a97b0c
