### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by alexandermarston** [alexandermarston/vnstat-dashboard#17]
The following notice is observed when running index.php.

PHP Notice:  Undefined variable: i in /home/alex/code/vnstat-dashboard/vnstat.php on line 111

[alex@nexus vnstat-dashboard]$ php --version
PHP 5.4.16 (cli) (built: Apr 12 2018 19:02:01)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

**Comment by piotrmacha** [comment]
Let me take this issue. A fix should be quick.

**Comment by rorkyendo** [comment]
i'am late to fix it?

**Comment by alexandermarston** [comment]
This has been fixed in b427952
