### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by izghitu** [alexandermarston/vnstat-dashboard#30]
Hi,

Does this vnstat dashboard work with PHP 7.2? I tried to set it up and I am getting countless lines like the below:
```
PHP message: PHP Notice:  Undefined offset: 2765375 in /home/user/vnstat-dashboard/vnstat.php on line 33
PHP message: PHP Notice:  Undefined offset: 2765376 in /home/user/vnstat-dashboard/vnstat.php on line 33
PHP message: PHP Notice:  Undefined offset: 2765377 in /home/user/vnstat-dashboard/vnstat.php on line 33
PHP message: PHP Notice:  Undefined offset: 2765378 in /home/user/vnstat-dashboard/vnstat.php on line 33
```
Please let me know.
Thanks

**Comment by cremesk** [comment]
Hey, you need this fix.
run under debian 9.6 and ubuntu 18.04
[fixed commit](https://github.com/cremesk/vnstat-dashboard/commit/b9601d9a25e6f8bab31baa100a1fea56cbac61ea)

**Comment by izghitu** [comment]
That did the trick. Thanks!
