### ISSUE TITLE
combined interface selections not possible 

### ISSUE THREAD

**Issue by soward** [alexandermarston/vnstat-dashboard#8]
If you have multiple interfaces you want to monitor, but would like to also see a roll-up of them, vnstat can accept multiple interfaces linked with a + and provide a roll-up; but the + is the separator for GET arguments. Adding rawurlencode and decode allows it work just fine. I can provide a pull as needed, though it's a 3 line change ( decode on line 39, encode on 29 and 31 of index.php ).

**Comment by alexandermarston** [comment]
Hi @soward I've added this as requested. Please test it and confirm it works as expected for your scenario.

Thanks

**Comment by alexandermarston** [comment]
Suggested feature no longer required and code removed from repository.
